version: '3.6'

services:
  tcat:
    container_name: tcat
    image: digitalmethodsinitiative/tcat:latest
    restart: always
    environment:
      - SERVERNAME=public
    ports:
      - 80:80
      - 443:443
    volumes:
      - tcat_data:/var/lib/mysql/

volumes:
  tcat_data: {}
